<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9c5a9ed12772223d3e336664965dfd77
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Tests\\' => 6,
        ),
        'L' => 
        array (
            'LastFmApi\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/matto1990/lastfm-api/tests',
        ),
        'LastFmApi\\' => 
        array (
            0 => __DIR__ . '/..' . '/matto1990/lastfm-api/src/lastfmapi',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9c5a9ed12772223d3e336664965dfd77::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9c5a9ed12772223d3e336664965dfd77::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
