<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit821418cf807c280aa597ba40aa35e21b
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Tests\\' => 6,
        ),
        'L' => 
        array (
            'LastFmApi\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/matto1990/lastfm-api/tests',
        ),
        'LastFmApi\\' => 
        array (
            0 => __DIR__ . '/..' . '/matto1990/lastfm-api/src/lastfmapi',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit821418cf807c280aa597ba40aa35e21b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit821418cf807c280aa597ba40aa35e21b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
