<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'QueryPath' => array($vendorDir . '/querypath/querypath/src'),
);
